In [34]:
import pandas as pd

green_df = pd.read_csv("green_tripdata_2025-08.csv")

print(green_df.shape)     
print(green_df.columns)    
print(green_df.head())

(46306, 21)
Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge',
       'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge',
       'cbd_congestion_fee'],
      dtype='object')
   VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0         2  2025-08-01 00:33:57   2025-08-01 00:58:10                  N
1         2  2025-08-01 00:01:00   2025-08-01 00:12:58                  N
2         2  2025-08-01 00:11:02   2025-08-01 00:16:06                  N
3         2  2025-08-01 00:44:09   2025-08-01 00:47:04                  N
4         2  2025-08-01 00:57:06   2025-08-01 01:05:32                  N

   RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0         1.0            70            82              1.0           2.44
1         1.0           130           216              1.0           4.06
2         1.0            74           263              1.0           2.09
3         1.0            42            41              1.0           0.53
4         1.0            75           239              1.0           2.28

   fare_amount  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0         21.9  ...      0.5        0.00           0.0        NaN
1         18.4  ...      0.5        0.00           0.0        NaN
2         10.0  ...      0.5        3.05           0.0        NaN
3          5.1  ...      0.5        0.00           0.0        NaN
4         12.1  ...      0.5        3.47           0.0        NaN

   improvement_surcharge  total_amount  payment_type  trip_type  \
0                    1.0         24.40           2.0        1.0
1                    1.0         20.90           2.0        1.0
2                    1.0         18.30           1.0        1.0
3                    1.0          7.60           2.0        1.0
4                    1.0         20.82           1.0        1.0

   congestion_surcharge  cbd_congestion_fee
0                  0.00                 0.0
1                  0.00                 0.0
2                  2.75                 0.0
3                  0.00                 0.0
4                  2.75                 0.0

[5 rows x 21 columns]

In [35]:
green_df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-08-01 00:33:57,2025-08-01 00:58:10,N,1.0,70,82,1.0,2.44,21.9,...,0.5,0.00,0.0,NaN,1.0,24.40,2.0,1.0,0.00,0.0
1,2,2025-08-01 00:01:00,2025-08-01 00:12:58,N,1.0,130,216,1.0,4.06,18.4,...,0.5,0.00,0.0,NaN,1.0,20.90,2.0,1.0,0.00,0.0
2,2,2025-08-01 00:11:02,2025-08-01 00:16:06,N,1.0,74,263,1.0,2.09,10.0,...,0.5,3.05,0.0,NaN,1.0,18.30,1.0,1.0,2.75,0.0
3,2,2025-08-01 00:44:09,2025-08-01 00:47:04,N,1.0,42,41,1.0,0.53,5.1,...,0.5,0.00,0.0,NaN,1.0,7.60,2.0,1.0,0.00,0.0
4,2,2025-08-01 00:57:06,2025-08-01 01:05:32,N,1.0,75,239,1.0,2.28,12.1,...,0.5,3.47,0.0,NaN,1.0,20.82,1.0,1.0,2.75,0.0

In [36]:
green_df = green_df[["lpep_pickup_datetime","lpep_dropoff_datetime","PULocationID","DOLocationID","total_amount"]]
green_df

,lpep_pickup_datetime,lpep_dropoff_datetime,PULocationID,DOLocationID,total_amount
0,2025-08-01 00:33:57,2025-08-01 00:58:10,70,82,24.40
1,2025-08-01 00:01:00,2025-08-01 00:12:58,130,216,20.90
2,2025-08-01 00:11:02,2025-08-01 00:16:06,74,263,18.30
3,2025-08-01 00:44:09,2025-08-01 00:47:04,42,41,7.60
4,2025-08-01 00:57:06,2025-08-01 01:05:32,75,239,20.82
...,...,...,...,...,...
46301,2025-08-31 22:56:00,2025-08-31 23:16:00,49,224,32.27
46302,2025-08-31 22:32:06,2025-08-31 22:51:08,70,95,16.00
46303,2025-08-31 22:39:31,2025-08-31 23:00:00,112,224,33.19
46304,2025-08-31 23:43:00,2025-09-01 00:03:00,74,32,30.31
46305,2025-08-31 23:32:00,2025-08-31 23:52:00,66,263,34.95

In [37]:
green_df.isna().sum()

lpep_pickup_datetime     0
lpep_dropoff_datetime    0
PULocationID             0
DOLocationID             0
total_amount             0
dtype: int64

In [38]:
green_df["lpep_pickup_datetime"] = pd.to_datetime(green_df["lpep_pickup_datetime"], errors="coerce")
green_df["lpep_dropoff_datetime"] = pd.to_datetime(green_df["lpep_dropoff_datetime"], errors="coerce")


green_df[["lpep_pickup_datetime", "lpep_dropoff_datetime"]].isna().sum()

lpep_pickup_datetime     0
lpep_dropoff_datetime    0
dtype: int64

In [39]:

invalid_time = green_df[green_df["lpep_dropoff_datetime"] <= green_df["lpep_pickup_datetime"]]
len(invalid_time)

38

In [40]:
green_df = green_df[green_df["lpep_dropoff_datetime"] > green_df["lpep_pickup_datetime"]]

In [41]:
green_df["trip_minutes"] = (
    (green_df["lpep_dropoff_datetime"] - green_df["lpep_pickup_datetime"]).dt.total_seconds() / 60
)


green_df[(green_df["trip_minutes"] < 5) & (green_df["trip_minutes"] > 180)]

/var/folders/nl/yhv930_54bq5qdztmb028v8r0000gn/T/ipykernel_22043/1838872597.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  green_df["trip_minutes"] = (

Empty DataFrame
Columns: [lpep_pickup_datetime, lpep_dropoff_datetime, PULocationID, DOLocationID, total_amount, trip_minutes]
Index: []

In [42]:
green_df = green_df[(green_df["trip_minutes"] >= 5) | (green_df["trip_minutes"] < 180)]
green_df

,lpep_pickup_datetime,lpep_dropoff_datetime,PULocationID,DOLocationID,total_amount,trip_minutes
0,2025-08-01 00:33:57,2025-08-01 00:58:10,70,82,24.40,24.216667
1,2025-08-01 00:01:00,2025-08-01 00:12:58,130,216,20.90,11.966667
2,2025-08-01 00:11:02,2025-08-01 00:16:06,74,263,18.30,5.066667
3,2025-08-01 00:44:09,2025-08-01 00:47:04,42,41,7.60,2.916667
4,2025-08-01 00:57:06,2025-08-01 01:05:32,75,239,20.82,8.433333
...,...,...,...,...,...,...
46301,2025-08-31 22:56:00,2025-08-31 23:16:00,49,224,32.27,20.000000
46302,2025-08-31 22:32:06,2025-08-31 22:51:08,70,95,16.00,19.033333
46303,2025-08-31 22:39:31,2025-08-31 23:00:00,112,224,33.19,20.483333
46304,2025-08-31 23:43:00,2025-09-01 00:03:00,74,32,30.31,20.000000
46305,2025-08-31 23:32:00,2025-08-31 23:52:00,66,263,34.95,20.000000

In [43]:
green_df = green_df[green_df["total_amount"] > 0]
green_df

,lpep_pickup_datetime,lpep_dropoff_datetime,PULocationID,DOLocationID,total_amount,trip_minutes
0,2025-08-01 00:33:57,2025-08-01 00:58:10,70,82,24.40,24.216667
1,2025-08-01 00:01:00,2025-08-01 00:12:58,130,216,20.90,11.966667
2,2025-08-01 00:11:02,2025-08-01 00:16:06,74,263,18.30,5.066667
3,2025-08-01 00:44:09,2025-08-01 00:47:04,42,41,7.60,2.916667
4,2025-08-01 00:57:06,2025-08-01 01:05:32,75,239,20.82,8.433333
...,...,...,...,...,...,...
46301,2025-08-31 22:56:00,2025-08-31 23:16:00,49,224,32.27,20.000000
46302,2025-08-31 22:32:06,2025-08-31 22:51:08,70,95,16.00,19.033333
46303,2025-08-31 22:39:31,2025-08-31 23:00:00,112,224,33.19,20.483333
46304,2025-08-31 23:43:00,2025-09-01 00:03:00,74,32,30.31,20.000000
46305,2025-08-31 23:32:00,2025-08-31 23:52:00,66,263,34.95,20.000000

In [44]:
green_df[["PULocationID", "DOLocationID"]].describe()

invalid_loc = green_df[
    (green_df["PULocationID"] <= 0) |
    (green_df["DOLocationID"] <= 0) |
    (green_df["PULocationID"] > 263) |
    (green_df["DOLocationID"] > 263)
]
len(invalid_loc), invalid_loc.head()

(905,
    lpep_pickup_datetime lpep_dropoff_datetime  PULocationID  DOLocationID  \
 8   2025-08-01 00:58:45   2025-08-01 00:58:48           181           264
 14  2025-08-01 00:11:25   2025-08-01 00:11:27           181           264
 24  2025-08-01 01:24:31   2025-08-01 01:51:12           205           265
 25  2025-08-01 01:27:58   2025-08-01 01:28:00           264           264
 29  2025-08-01 01:14:08   2025-08-01 01:14:11            74           264

     total_amount  trip_minutes
 8          81.05      0.050000
 14         61.80      0.033333
 24         32.80     26.683333
 25         16.80      0.033333
 29         16.00      0.050000  )

In [45]:
green_df = green_df[(green_df['PULocationID']<=263) & (green_df['PULocationID']>=1)]
green_df = green_df[(green_df['DOLocationID']<=263) & (green_df['DOLocationID']>=1)]

In [46]:
green_df = green_df.rename(columns={'lpep_pickup_datetime': 'pickup_datetime', 'lpep_dropoff_datetime': 'dropoff_datetime', 'PULocationID': 'pickup_location', 'DOLocationID': 'dropoff_location '})

In [47]:
green_df = green_df.drop(columns=["trip_minutes"])

In [48]:
green_df

,pickup_datetime,dropoff_datetime,pickup_location,dropoff_location,total_amount
0,2025-08-01 00:33:57,2025-08-01 00:58:10,70,82,24.40
1,2025-08-01 00:01:00,2025-08-01 00:12:58,130,216,20.90
2,2025-08-01 00:11:02,2025-08-01 00:16:06,74,263,18.30
3,2025-08-01 00:44:09,2025-08-01 00:47:04,42,41,7.60
4,2025-08-01 00:57:06,2025-08-01 01:05:32,75,239,20.82
...,...,...,...,...,...
46301,2025-08-31 22:56:00,2025-08-31 23:16:00,49,224,32.27
46302,2025-08-31 22:32:06,2025-08-31 22:51:08,70,95,16.00
46303,2025-08-31 22:39:31,2025-08-31 23:00:00,112,224,33.19
46304,2025-08-31 23:43:00,2025-09-01 00:03:00,74,32,30.31
46305,2025-08-31 23:32:00,2025-08-31 23:52:00,66,263,34.95

In [49]:
green_df.to_csv('green_cleaned_df.csv')