In [1]:
import pandas as pd

yellow_df = pd.read_parquet("yellow_tripdata_2025-08.parquet")

print(yellow_df.shape)     
print(yellow_df.columns)    
print(yellow_df.head())

(3574091, 20)
Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='object')
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         2  2025-08-01 00:52:23   2025-08-01 01:12:20              1.0
1         2  2025-08-01 00:03:01   2025-08-01 00:15:33              2.0
2         7  2025-08-01 00:24:38   2025-08-01 00:24:38              2.0
3         7  2025-08-01 00:48:19   2025-08-01 00:48:19              1.0
4         2  2025-08-01 00:25:34   2025-08-01 00:33:18              1.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           8.44         1.0                  N           138           141
1           4.98         1.0                  N           138           193
2           1.89         1.0                  N           249            45
3           2.35         1.0                  N            79           229
4           2.14         1.0                  N            43            48

   payment_type  fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
0             1         33.8    6.0      0.5        5.00          6.94
1             1         21.2    6.0      0.5        0.00          0.00
2             1         14.2    0.0      0.5        3.99          0.00
3             1         11.4    0.0      0.5        3.43          0.00
4             1         11.4    1.0      0.5        2.57          0.00

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0         57.49                   2.5         1.75
1                    1.0         30.45                   0.0         1.75
2                    1.0         23.94                   2.5         0.00
3                    1.0         20.58                   2.5         0.00
4                    1.0         19.72                   2.5         0.00

   cbd_congestion_fee
0                0.00
1                0.00
2                0.75
3                0.75
4                0.75

In [2]:
yellow_df.head(5)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2025-08-01 00:52:23,2025-08-01 01:12:20,1.0,8.44,1.0,N,138,141,1,33.8,6.0,0.5,5.00,6.94,1.0,57.49,2.5,1.75,0.00
1,2,2025-08-01 00:03:01,2025-08-01 00:15:33,2.0,4.98,1.0,N,138,193,1,21.2,6.0,0.5,0.00,0.00,1.0,30.45,0.0,1.75,0.00
2,7,2025-08-01 00:24:38,2025-08-01 00:24:38,2.0,1.89,1.0,N,249,45,1,14.2,0.0,0.5,3.99,0.00,1.0,23.94,2.5,0.00,0.75
3,7,2025-08-01 00:48:19,2025-08-01 00:48:19,1.0,2.35,1.0,N,79,229,1,11.4,0.0,0.5,3.43,0.00,1.0,20.58,2.5,0.00,0.75
4,2,2025-08-01 00:25:34,2025-08-01 00:33:18,1.0,2.14,1.0,N,43,48,1,11.4,1.0,0.5,2.57,0.00,1.0,19.72,2.5,0.00,0.75

In [4]:
green_df = pd.read_parquet("green_tripdata_2025-08.parquet")

print(green_df.shape)       
print(green_df.columns) 
print(green_df.head())

(46306, 21)
Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge',
       'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge',
       'cbd_congestion_fee'],
      dtype='object')
   VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0         2  2025-08-01 00:33:57   2025-08-01 00:58:10                  N
1         2  2025-08-01 00:01:00   2025-08-01 00:12:58                  N
2         2  2025-08-01 00:11:02   2025-08-01 00:16:06                  N
3         2  2025-08-01 00:44:09   2025-08-01 00:47:04                  N
4         2  2025-08-01 00:57:06   2025-08-01 01:05:32                  N

   RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0         1.0            70            82              1.0           2.44
1         1.0           130           216              1.0           4.06
2         1.0            74           263              1.0           2.09
3         1.0            42            41              1.0           0.53
4         1.0            75           239              1.0           2.28

   fare_amount  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0         21.9  ...      0.5        0.00           0.0        NaN
1         18.4  ...      0.5        0.00           0.0        NaN
2         10.0  ...      0.5        3.05           0.0        NaN
3          5.1  ...      0.5        0.00           0.0        NaN
4         12.1  ...      0.5        3.47           0.0        NaN

   improvement_surcharge  total_amount  payment_type  trip_type  \
0                    1.0         24.40           2.0        1.0
1                    1.0         20.90           2.0        1.0
2                    1.0         18.30           1.0        1.0
3                    1.0          7.60           2.0        1.0
4                    1.0         20.82           1.0        1.0

   congestion_surcharge  cbd_congestion_fee
0                  0.00                 0.0
1                  0.00                 0.0
2                  2.75                 0.0
3                  0.00                 0.0
4                  2.75                 0.0

[5 rows x 21 columns]

In [5]:
green_df.head(5)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-08-01 00:33:57,2025-08-01 00:58:10,N,1.0,70,82,1.0,2.44,21.9,...,0.5,0.00,0.0,NaN,1.0,24.40,2.0,1.0,0.00,0.0
1,2,2025-08-01 00:01:00,2025-08-01 00:12:58,N,1.0,130,216,1.0,4.06,18.4,...,0.5,0.00,0.0,NaN,1.0,20.90,2.0,1.0,0.00,0.0
2,2,2025-08-01 00:11:02,2025-08-01 00:16:06,N,1.0,74,263,1.0,2.09,10.0,...,0.5,3.05,0.0,NaN,1.0,18.30,1.0,1.0,2.75,0.0
3,2,2025-08-01 00:44:09,2025-08-01 00:47:04,N,1.0,42,41,1.0,0.53,5.1,...,0.5,0.00,0.0,NaN,1.0,7.60,2.0,1.0,0.00,0.0
4,2,2025-08-01 00:57:06,2025-08-01 01:05:32,N,1.0,75,239,1.0,2.28,12.1,...,0.5,3.47,0.0,NaN,1.0,20.82,1.0,1.0,2.75,0.0

In [6]:
fhvhv_df = pd.read_parquet("fhvhv_tripdata_2025-08.parquet")

print(fhvhv_df.shape)      
print(fhvhv_df.columns)  
print(fhvhv_df.head())

(19271461, 25)
Index(['hvfhs_license_num', 'dispatching_base_num', 'originating_base_num',
       'request_datetime', 'on_scene_datetime', 'pickup_datetime',
       'dropoff_datetime', 'PULocationID', 'DOLocationID', 'trip_miles',
       'trip_time', 'base_passenger_fare', 'tolls', 'bcf', 'sales_tax',
       'congestion_surcharge', 'airport_fee', 'tips', 'driver_pay',
       'shared_request_flag', 'shared_match_flag', 'access_a_ride_flag',
       'wav_request_flag', 'wav_match_flag', 'cbd_congestion_fee'],
      dtype='object')
  hvfhs_license_num dispatching_base_num originating_base_num  \
0            HV0003               B03404               B03404
1            HV0003               B03404               B03404
2            HV0003               B03404               B03404
3            HV0003               B03404               B03404
4            HV0003               B03404               B03404

     request_datetime   on_scene_datetime     pickup_datetime  \
0 2025-08-01 00:07:01 2025-08-01 00:09:06 2025-08-01 00:09:29
1 2025-08-01 00:31:28 2025-08-01 00:35:30 2025-08-01 00:35:50
2 2025-08-01 00:53:16 2025-08-01 00:54:54 2025-08-01 00:56:55
3 2025-08-01 00:52:57 2025-08-01 00:54:47 2025-08-01 00:56:10
4 2025-08-01 00:06:10 2025-08-01 00:09:20 2025-08-01 00:09:44

     dropoff_datetime  PULocationID  DOLocationID  trip_miles  ...  \
0 2025-08-01 00:22:28           113           158        1.53  ...
1 2025-08-01 00:46:56           144            68        2.06  ...
2 2025-08-01 01:18:05           249           137        2.97  ...
3 2025-08-01 01:02:18            68           158        1.27  ...
4 2025-08-01 00:26:07           174           244        8.27  ...

   congestion_surcharge  airport_fee  tips  driver_pay  shared_request_flag  \
0                  2.75          0.0   0.0       27.61                    N
1                  2.75          0.0   0.0       10.39                    N
2                  2.75          0.0   0.0       18.05                    N
3                  2.75          0.0   0.0        7.29                    N
4                  0.00          0.0   0.0       21.05                    N

   shared_match_flag  access_a_ride_flag  wav_request_flag  wav_match_flag  \
0                  N                   N                 N               N
1                  N                   N                 N               N
2                  N                   N                 N               N
3                  N                   N                 N               N
4                  N                   N                 N               N

  cbd_congestion_fee
0                1.5
1                1.5
2                1.5
3                1.5
4                0.0

[5 rows x 25 columns]

In [7]:
fhvhv_df.head(5)

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,...,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag,cbd_congestion_fee
0,HV0003,B03404,B03404,2025-08-01 00:07:01,2025-08-01 00:09:06,2025-08-01 00:09:29,2025-08-01 00:22:28,113,158,1.53,...,2.75,0.0,0.0,27.61,N,N,N,N,N,1.5
1,HV0003,B03404,B03404,2025-08-01 00:31:28,2025-08-01 00:35:30,2025-08-01 00:35:50,2025-08-01 00:46:56,144,68,2.06,...,2.75,0.0,0.0,10.39,N,N,N,N,N,1.5
2,HV0003,B03404,B03404,2025-08-01 00:53:16,2025-08-01 00:54:54,2025-08-01 00:56:55,2025-08-01 01:18:05,249,137,2.97,...,2.75,0.0,0.0,18.05,N,N,N,N,N,1.5
3,HV0003,B03404,B03404,2025-08-01 00:52:57,2025-08-01 00:54:47,2025-08-01 00:56:10,2025-08-01 01:02:18,68,158,1.27,...,2.75,0.0,0.0,7.29,N,N,N,N,N,1.5
4,HV0003,B03404,B03404,2025-08-01 00:06:10,2025-08-01 00:09:20,2025-08-01 00:09:44,2025-08-01 00:26:07,174,244,8.27,...,0.00,0.0,0.0,21.05,N,N,N,N,N,0.0

In [ ]:
import pandas as pd
df = pd.read_parquet("yellow_tripdata_2025-08.parquet")
df.to_csv("yellow_tripdata_2025-08.csv", index=False)

In [3]:
import pandas as pd
df = pd.read_parquet("green_tripdata_2025-08.parquet")
df.to_csv("green_tripdata_2025-08.csv", index=False)

In [4]:
import pandas as pd
df = pd.read_parquet("fhvhv_tripdata_2025-08.parquet")
df.to_csv("fhvhv_tripdata_2025-08.csv", index=False)

In [1]:
import pandas as pd
df = pd.read_parquet("yellow_tripdata_2025-08.parquet")
df.to_csv("yellow_tripdata_2025-08.csv", index=False)

In [2]:
pd.read_csv("yellow_tripdata_2025-08.csv")

/var/folders/rq/d1f380z1435dgk98n9b9hwz40000gn/T/ipykernel_6624/1313048019.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv("yellow_tripdata_2025-08.csv")

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2025-08-01 00:52:23,2025-08-01 01:12:20,1.0,8.44,1.0,N,138,141,1,33.80,6.0,0.5,5.00,6.94,1.0,57.49,2.5,1.75,0.00
1,2,2025-08-01 00:03:01,2025-08-01 00:15:33,2.0,4.98,1.0,N,138,193,1,21.20,6.0,0.5,0.00,0.00,1.0,30.45,0.0,1.75,0.00
2,7,2025-08-01 00:24:38,2025-08-01 00:24:38,2.0,1.89,1.0,N,249,45,1,14.20,0.0,0.5,3.99,0.00,1.0,23.94,2.5,0.00,0.75
3,7,2025-08-01 00:48:19,2025-08-01 00:48:19,1.0,2.35,1.0,N,79,229,1,11.40,0.0,0.5,3.43,0.00,1.0,20.58,2.5,0.00,0.75
4,2,2025-08-01 00:25:34,2025-08-01 00:33:18,1.0,2.14,1.0,N,43,48,1,11.40,1.0,0.5,2.57,0.00,1.0,19.72,2.5,0.00,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3574086,2,2025-08-31 23:40:30,2025-08-31 23:58:48,NaN,3.12,NaN,NaN,65,228,0,21.53,0.0,0.5,0.00,0.00,1.0,23.03,NaN,NaN,0.00
3574087,2,2025-08-31 23:10:26,2025-08-31 23:29:01,NaN,5.92,NaN,NaN,236,148,0,21.78,0.0,0.5,0.00,0.00,1.0,26.53,NaN,NaN,0.75
3574088,2,2025-08-31 23:04:21,2025-08-31 23:25:21,NaN,4.10,NaN,NaN,148,48,0,-4.75,0.0,0.5,0.00,0.00,1.0,5.83,NaN,NaN,0.75
3574089,2,2025-08-31 23:44:26,2025-08-31 23:44:42,NaN,0.02,NaN,NaN,107,107,0,12.67,0.0,0.5,0.00,0.00,1.0,17.42,NaN,NaN,0.75
3574090,2,2025-08-31 23:11:01,2025-08-31 23:31:07,NaN,5.07,NaN,NaN,65,68,0,-4.75,0.0,0.5,0.00,0.00,1.0,10.00,NaN,NaN,0.75