In [ ]:
import pandas as pd

yellow_df = pd.read_csv("yellow_tripdata_2025-08.csv")

print(yellow_df.shape)      
print(yellow_df.columns)    
print(yellow_df.head())

/var/folders/rq/d1f380z1435dgk98n9b9hwz40000gn/T/ipykernel_5221/1840432165.py:3: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  yellow_df = pd.read_csv("yellow_tripdata_2025-08.csv")

(3574091, 20)
Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='object')
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         2  2025-08-01 00:52:23   2025-08-01 01:12:20              1.0
1         2  2025-08-01 00:03:01   2025-08-01 00:15:33              2.0
2         7  2025-08-01 00:24:38   2025-08-01 00:24:38              2.0
3         7  2025-08-01 00:48:19   2025-08-01 00:48:19              1.0
4         2  2025-08-01 00:25:34   2025-08-01 00:33:18              1.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           8.44         1.0                  N           138           141
1           4.98         1.0                  N           138           193
2           1.89         1.0                  N           249            45
3           2.35         1.0                  N            79           229
4           2.14         1.0                  N            43            48

   payment_type  fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
0             1         33.8    6.0      0.5        5.00          6.94
1             1         21.2    6.0      0.5        0.00          0.00
2             1         14.2    0.0      0.5        3.99          0.00
3             1         11.4    0.0      0.5        3.43          0.00
4             1         11.4    1.0      0.5        2.57          0.00

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0         57.49                   2.5         1.75
1                    1.0         30.45                   0.0         1.75
2                    1.0         23.94                   2.5         0.00
3                    1.0         20.58                   2.5         0.00
4                    1.0         19.72                   2.5         0.00

   cbd_congestion_fee
0                0.00
1                0.00
2                0.75
3                0.75
4                0.75

In [2]:
yellow_df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2025-08-01 00:52:23,2025-08-01 01:12:20,1.0,8.44,1.0,N,138,141,1,33.8,6.0,0.5,5.00,6.94,1.0,57.49,2.5,1.75,0.00
1,2,2025-08-01 00:03:01,2025-08-01 00:15:33,2.0,4.98,1.0,N,138,193,1,21.2,6.0,0.5,0.00,0.00,1.0,30.45,0.0,1.75,0.00
2,7,2025-08-01 00:24:38,2025-08-01 00:24:38,2.0,1.89,1.0,N,249,45,1,14.2,0.0,0.5,3.99,0.00,1.0,23.94,2.5,0.00,0.75
3,7,2025-08-01 00:48:19,2025-08-01 00:48:19,1.0,2.35,1.0,N,79,229,1,11.4,0.0,0.5,3.43,0.00,1.0,20.58,2.5,0.00,0.75
4,2,2025-08-01 00:25:34,2025-08-01 00:33:18,1.0,2.14,1.0,N,43,48,1,11.4,1.0,0.5,2.57,0.00,1.0,19.72,2.5,0.00,0.75

In [4]:
yellow_df = yellow_df[["tpep_pickup_datetime","tpep_dropoff_datetime","PULocationID","DOLocationID","total_amount"]]

In [5]:
yellow_df

,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID,total_amount
0,2025-08-01 00:52:23,2025-08-01 01:12:20,138,141,57.49
1,2025-08-01 00:03:01,2025-08-01 00:15:33,138,193,30.45
2,2025-08-01 00:24:38,2025-08-01 00:24:38,249,45,23.94
3,2025-08-01 00:48:19,2025-08-01 00:48:19,79,229,20.58
4,2025-08-01 00:25:34,2025-08-01 00:33:18,43,48,19.72
...,...,...,...,...,...
41758,2025-08-01 15:54:49,2025-08-01 16:10:31,233,144,22.35
41759,2025-08-01 15:39:00,2025-08-01 15:46:45,140,141,15.12
41760,2025-08-01 15:52:36,2025-08-01 15:59:42,140,229,15.35
41761,2025-08-01 15:35:02,2025-08-01 15:53:56,239,90,28.62
41762,2025-08-01 15:44:40,2025-08-01 15:46:14,162,237,8.45

In [ ]:
# check missing values
yellow_df.isna().sum()

# check if we have NaN
yellow_df.isna().any()

tpep_pickup_datetime     False
tpep_dropoff_datetime    False
PULocationID             False
DOLocationID             False
total_amount             False
dtype: bool

In [ ]:
# convert to datetime 
yellow_df["tpep_pickup_datetime"] = pd.to_datetime(yellow_df["tpep_pickup_datetime"], errors="coerce")
yellow_df["tpep_dropoff_datetime"] = pd.to_datetime(yellow_df["tpep_dropoff_datetime"], errors="coerce")

# check how many NaT do we have
yellow_df[["tpep_pickup_datetime", "tpep_dropoff_datetime"]].isna().sum()

tpep_pickup_datetime     0
tpep_dropoff_datetime    0
dtype: int64

In [ ]:
# dropoff should be later than pickup 
invalid_time = yellow_df[yellow_df["tpep_dropoff_datetime"] <= yellow_df["tpep_pickup_datetime"]]
len(invalid_time)  # rows abnormal?

invalid_time

,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID,total_amount
2,2025-08-01 00:24:38,2025-08-01 00:24:38,249,45,23.94
3,2025-08-01 00:48:19,2025-08-01 00:48:19,79,229,20.58
48,2025-08-01 00:56:52,2025-08-01 00:56:52,144,264,11.55
139,2025-08-01 00:18:29,2025-08-01 00:18:29,246,90,12.95
140,2025-08-01 00:36:13,2025-08-01 00:36:13,50,50,14.10
...,...,...,...,...,...
41528,2025-08-01 15:04:46,2025-08-01 15:04:46,87,232,9.15
41529,2025-08-01 15:19:24,2025-08-01 15:19:24,148,234,17.15
41530,2025-08-01 15:44:13,2025-08-01 15:44:13,234,50,29.46
41557,2025-08-01 15:59:42,2025-08-01 15:59:42,230,138,87.47
41648,2025-08-01 15:31:32,2025-08-01 15:31:32,262,138,64.73

we have 770 rows of invalid datetime. So we need to filter them out.

In [11]:
yellow_df = yellow_df[yellow_df["tpep_dropoff_datetime"] > yellow_df["tpep_pickup_datetime"]]

In [ ]:
# trip time
yellow_df["trip_minutes"] = (
    (yellow_df["tpep_dropoff_datetime"] - yellow_df["tpep_pickup_datetime"]).dt.total_seconds() / 60
)

yellow_df["trip_minutes"].describe()

# extreme values of trip time
yellow_df[(yellow_df["trip_minutes"] < 1) | (yellow_df["trip_minutes"] > 180)]

/var/folders/rq/d1f380z1435dgk98n9b9hwz40000gn/T/ipykernel_5221/3893131089.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yellow_df["trip_minutes"] = (

,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID,total_amount,trip_minutes
136,2025-08-01 00:18:31,2025-08-01 00:19:14,148,148,8.75,0.716667
171,2025-08-01 00:15:21,2025-08-01 00:15:52,263,141,8.00,0.516667
184,2025-08-01 00:48:32,2025-08-01 00:48:37,170,170,-74.75,0.083333
185,2025-08-01 00:48:32,2025-08-01 00:48:37,170,170,74.75,0.083333
224,2025-08-01 00:12:43,2025-08-01 00:12:45,142,142,13.00,0.033333
...,...,...,...,...,...,...
41260,2025-08-01 15:02:02,2025-08-01 15:02:06,13,13,32.70,0.066667
41315,2025-08-01 15:46:29,2025-08-01 15:46:36,75,75,4.50,0.116667
41396,2025-08-01 15:39:04,2025-08-01 15:39:12,170,164,74.75,0.133333
41407,2025-08-01 15:04:59,2025-08-01 15:05:04,211,211,105.25,0.083333
41649,2025-08-01 13:00:47,2025-08-02 12:07:46,141,140,14.88,1386.983333

In [14]:
yellow_df = yellow_df[(yellow_df["trip_minutes"] > 5) | (yellow_df["trip_minutes"] < 180)]

In [15]:
yellow_df

,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID,total_amount,trip_minutes
0,2025-08-01 00:52:23,2025-08-01 01:12:20,138,141,57.49,19.950000
1,2025-08-01 00:03:01,2025-08-01 00:15:33,138,193,30.45,12.533333
4,2025-08-01 00:25:34,2025-08-01 00:33:18,43,48,19.72,7.733333
5,2025-08-01 00:16:36,2025-08-01 00:33:41,114,230,24.15,17.083333
6,2025-08-01 00:56:02,2025-08-01 01:15:37,163,13,31.45,19.583333
...,...,...,...,...,...,...
41758,2025-08-01 15:54:49,2025-08-01 16:10:31,233,144,22.35,15.700000
41759,2025-08-01 15:39:00,2025-08-01 15:46:45,140,141,15.12,7.750000
41760,2025-08-01 15:52:36,2025-08-01 15:59:42,140,229,15.35,7.100000
41761,2025-08-01 15:35:02,2025-08-01 15:53:56,239,90,28.62,18.900000
41762,2025-08-01 15:44:40,2025-08-01 15:46:14,162,237,8.45,1.566667

In [ ]:
# .describe
yellow_df["total_amount"].describe()

# negative value?
# yellow_df[(yellow_df["total_amount"] < 0) | (yellow_df["total_amount"] > 500)]
yellow_df = yellow_df[yellow_df["total_amount"] > 0]

In [20]:
yellow_df

,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID,total_amount,trip_minutes
0,2025-08-01 00:52:23,2025-08-01 01:12:20,138,141,57.49,19.950000
1,2025-08-01 00:03:01,2025-08-01 00:15:33,138,193,30.45,12.533333
4,2025-08-01 00:25:34,2025-08-01 00:33:18,43,48,19.72,7.733333
5,2025-08-01 00:16:36,2025-08-01 00:33:41,114,230,24.15,17.083333
6,2025-08-01 00:56:02,2025-08-01 01:15:37,163,13,31.45,19.583333
...,...,...,...,...,...,...
41758,2025-08-01 15:54:49,2025-08-01 16:10:31,233,144,22.35,15.700000
41759,2025-08-01 15:39:00,2025-08-01 15:46:45,140,141,15.12,7.750000
41760,2025-08-01 15:52:36,2025-08-01 15:59:42,140,229,15.35,7.100000
41761,2025-08-01 15:35:02,2025-08-01 15:53:56,239,90,28.62,18.900000
41762,2025-08-01 15:44:40,2025-08-01 15:46:14,162,237,8.45,1.566667

In [ ]:
# ID should be integer&non-negative, also we have only 265 locations
yellow_df[["PULocationID", "DOLocationID"]].describe()

invalid_loc = yellow_df[
    (yellow_df["PULocationID"] <= 0) |
    (yellow_df["DOLocationID"] <= 0) |
    (yellow_df["PULocationID"] > 265) |
    (yellow_df["DOLocationID"] > 265)
]
len(invalid_loc), invalid_loc.head()

(0,
 Empty DataFrame
 Columns: [tpep_pickup_datetime, tpep_dropoff_datetime, PULocationID, DOLocationID, total_amount, trip_minutes]
 Index: [])

In [25]:
yellow_df.drop(columns=["trip_minutes"])

,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID,total_amount
0,2025-08-01 00:52:23,2025-08-01 01:12:20,138,141,57.49
1,2025-08-01 00:03:01,2025-08-01 00:15:33,138,193,30.45
4,2025-08-01 00:25:34,2025-08-01 00:33:18,43,48,19.72
5,2025-08-01 00:16:36,2025-08-01 00:33:41,114,230,24.15
6,2025-08-01 00:56:02,2025-08-01 01:15:37,163,13,31.45
...,...,...,...,...,...
41758,2025-08-01 15:54:49,2025-08-01 16:10:31,233,144,22.35
41759,2025-08-01 15:39:00,2025-08-01 15:46:45,140,141,15.12
41760,2025-08-01 15:52:36,2025-08-01 15:59:42,140,229,15.35
41761,2025-08-01 15:35:02,2025-08-01 15:53:56,239,90,28.62
41762,2025-08-01 15:44:40,2025-08-01 15:46:14,162,237,8.45

In [26]:
yellow_df.to_csv('yellow_cleaned_df.csv')